Repository LO-CO-CO/LOCOCO-CLIENT, pull requests merged in 2025-10, with the labels that each got.

#428 Feat(web): fix my page edit profile
  apps/web/app/[locale]/(with-layout)/my-page/edit-profile/page.tsx
  apps/web/app/[locale]/(with-layout)/my-page/hooks/use-profile-api.ts
  apps/web/app/[locale]/(with-layout)/sign-up/creator/components/community-name.tsx
  apps/web/components/forms/FormSection.tsx
Labels: ✨ Feature, 🫐 동희, Fix

#430 Feat(web): how it work image 및 text 추가
  apps/web/app/[locale]/(with-layout)/how-it-work/components/creators.tsx
  apps/web/messages/en.json
  packages/design-system/src/icons/fill/components/Crown.tsx
  packages/design-system/src/icons/fill/components/PersonTime.tsx
  packages/design-system/src/icons/fill/components/Present.tsx
  packages/design-system/src/icons/fill/components/index.tsx
  packages/design-system/src/icons/fill/svg/crown.svg
  packages/design-system/src/icons/fill/svg/person_time.svg
  packages/design-system/src/icons/fill/svg/present.svg
Labels: ✨ Feature, 🫐 동희

#433 Feat(web): gnb 기능 추가
  apps/web/components/gnb/api/index.ts
  apps/web/components/gnb/gnb-auth.tsx
  apps/web/components/gnb/hooks/useAuthInfo.ts
  apps/web/hooks/use-auth.ts
  apps/web/swagger-codegen/data-contracts.ts
  apps/web/utils/action/auth.ts
Labels: ✨ Feature, 🥥 제성

#426 Feat(web): 지원자 승인 api 연결 및 empty뷰 추가
  apps/web/app/[locale]/(with-layout)/brand/applicants/apis/index.ts
  apps/web/app/[locale]/(with-layout)/brand/applicants/components/applicants-table.tsx
  apps/web/app/[locale]/(with-layout)/brand/applicants/components/approve-status-select.tsx
  apps/web/app/[locale]/(with-layout)/brand/applicants/hooks/query.ts
  apps/web/app/[locale]/(with-layout)/brand/applicants/page.client.tsx
  apps/web/app/[locale]/(with-layout)/brand/layout.tsx
  apps/web/public/applicants-empty.svg
  apps/web/public/campaign-empty.svg
Labels: ✨ Feature, 🍋 재훈

#435 Feat(web): 브랜드 마이페이지 - 캠페인 생성 페이지 수정
  apps/web/app/[locale]/(with-layout)/brand/component/create-campaign/campaign-due-date.tsx
  apps/web/app/[locale]/(with-layout)/brand/component/create-campaign/social-chip.tsx
  apps/web/app/[locale]/(with-layout)/brand/create-campaign/api/index.ts
  apps/web/app/[locale]/(with-layout)/brand/hooks/usePlatformSelection.ts
  apps/web/components/campaign/campaign-upload-media.tsx
  apps/web/components/drag-drop/DargDropArea.tsx
  apps/web/components/forms/FormSection.tsx
Labels: 🥥 제성, Fix

#423 Feat(web): 브랜드 마이페이지 - 프로필 편집 api 연동
  apps/web/app/[locale]/(with-layout)/brand/profile/api/index.ts
  apps/web/app/[locale]/(with-layout)/brand/profile/component/basic-info.tsx
  apps/web/app/[locale]/(with-layout)/brand/profile/component/image-section.tsx
  apps/web/app/[locale]/(with-layout)/brand/profile/hooks/useBrandProfile.ts
  apps/web/app/[locale]/(with-layout)/brand/profile/hooks/useEditBrandProfile.ts
  apps/web/app/[locale]/(with-layout)/brand/profile/page.tsx
  apps/web/components/forms/TextFormField.tsx
  apps/web/schema/brand-profile-edit.ts
  apps/web/swagger-codegen/data-contracts.ts
Labels: ✨ Feature, 🥥 제성

#437 Feature/#436/brand side bar
  apps/web/app/[locale]/(with-layout)/brand/[brandId]/applicants/apis/index.ts
  apps/web/app/[locale]/(with-layout)/brand/[brandId]/applicants/components/applicants-table.tsx
  apps/web/app/[locale]/(with-layout)/brand/[brandId]/applicants/components/approve-status-select.tsx
  apps/web/app/[locale]/(with-layout)/brand/[brandId]/applicants/components/campaign-select.tsx
  apps/web/app/[locale]/(with-layout)/brand/[brandId]/applicants/components/column/applied-date-column.tsx
  apps/web/app/[locale]/(with-layout)/brand/[brandId]/applicants/components/column/approve-status-column.tsx
  apps/web/app/[locale]/(with-layout)/brand/[brandId]/applicants/components/column/campaign-count-column.tsx
  apps/web/app/[locale]/(with-layout)/brand/[brandId]/applicants/components/column/creator-profile-column.tsx
  apps/web/app/[locale]/(with-layout)/brand/[brandId]/applicants/components/column/follower-count-column.tsx
  apps/web/app/[locale]/(with-layout)/brand/[brandId]/applicants/hooks/query.ts
  apps/web/app/[locale]/(with-layout)/brand/[brandId]/applicants/page.client.tsx
  apps/web/app/[locale]/(with-layout)/brand/[brandId]/applicants/page.tsx
  apps/web/app/[locale]/(with-layout)/brand/[brandId]/applicants/types/index.ts
  apps/web/app/[locale]/(with-layout)/brand/[brandId]/applicants/utils/follower-count-formatter.ts
  apps/web/app/[locale]/(with-layout)/brand/[brandId]/applicants/utils/ko-date-range-formatter.ts
  apps/web/app/[locale]/(with-layout)/brand/component/client-side-bar/ClientSideBar.tsx
  apps/web/app/[locale]/(with-layout)/brand/constant/querykey.ts
  apps/web/app/[locale]/(with-layout)/brand/hooks/useBrandProfile.ts
  apps/web/app/[locale]/(with-layout)/brand/layout.tsx
  apps/web/app/[locale]/(with-layout)/my-page/edit-profile/page.tsx
  apps/web/messages/en.json
  apps/web/messages/es.json
  apps/web/messages/ko.json
  apps/web/swagger-codegen/SnsConnection.ts
  apps/web/swagger-codegen/data-contracts.ts
Labels: ✨ Feature, 🫐 동희

#439 Fix(web): 임시저장 이미지 담는 변수 초기화 조건 추가
  apps/web/components/campaign/campaign-upload-media.tsx
Labels: 🥥 제성, Fix

#447 Fix(web): 구글 회원가입 로딩에서는 gnb 레이아웃 제외
  apps/web/app/[locale]/(with-layout)/login-google/loading/page.tsx
  apps/web/app/[locale]/login-google/loading/page.tsx
Labels: 🍒 희연, Fix

#452 Fix(web): creator mypage 번역 수정
  apps/web/app/[locale]/(with-layout)/my-page/edit-profile/page.tsx
  apps/web/messages/en.json
  apps/web/messages/es.json
  apps/web/messages/ko.json
Labels: 🫐 동희, Fix

#450 Feat(web): gnb 로그아웃 이벤트 추가 및 Card, 캠페인 생성 QA
  apps/web/app/[locale]/(with-layout)/(home)/components/home-section-campaign.tsx
  apps/web/app/[locale]/(with-layout)/brand/component/create-campaign/dynamic-inpt.tsx
  apps/web/components/campaign/campaign-grid.tsx
  apps/web/components/card/BracketChip.tsx
  apps/web/components/card/Card.tsx
  apps/web/components/card/utils/getChipVariantByDate.ts
  apps/web/components/ui/dropdown-menu.tsx
  apps/web/hooks/use-auth.ts
  apps/web/schema/create-campaign-schema.ts
Labels: ✨ Feature, 🥥 제성, Fix

#456 Feat(Web): 회원가입 페이지 엣지 케이스 QA
  apps/web/app/[locale]/(with-layout)/login-google/hooks/useRoleSetup.ts
  apps/web/app/[locale]/(with-layout)/login-google/utils/role-api.ts
  apps/web/app/[locale]/(with-layout)/login-google/utils/role-storage.ts
  apps/web/app/[locale]/(with-layout)/sign-up/components/select-role-modal.tsx
  apps/web/app/api/auth/google/login/route.ts
  apps/web/components/forms/SnsConnection.tsx
  apps/web/components/gnb/gnb-auth.tsx
Labels: 🍒 희연

#466 [Refactor/#465] my page campaign card 공통 컴포넌트로 change
  apps/web/app/[locale]/(with-layout)/my-page/components/card/Barket.tsx
  apps/web/app/[locale]/(with-layout)/my-page/components/card/Card.tsx
  apps/web/app/[locale]/(with-layout)/my-page/components/client-sidebar/client-sidebar.tsx
  apps/web/app/[locale]/(with-layout)/my-page/my-campaign/page.tsx
  apps/web/components/card/BracketChip.tsx
  apps/web/components/card/card-my-page.tsx
  apps/web/messages/en.json
  apps/web/messages/es.json
  apps/web/messages/ko.json
Labels: ✨ Feature, 🫐 동희

#468 Feat(web): gnb, howitwork qa
  apps/web/components/gnb/gnb-auth.tsx
  apps/web/messages/en.json
  apps/web/messages/es.json
  apps/web/messages/ko.json
Labels: ✨ Feature, 🫐 동희

#470 Feat(web): 새 캠페인 생성 페이지 조건 수정
  apps/web/app/[locale]/(with-layout)/brand/create-campaign/component/campaign-form.tsx
  apps/web/components/campaign/campaign-upload-media.tsx
  apps/web/schema/create-campaign-schema.ts
Labels: 🥥 제성, Fix

#472 fix(web): middleware.ts early return으로 인해 locale을 반환하지 않는 문제 해결
  apps/web/app/[locale]/(with-layout)/brand/layout.tsx
  apps/web/constants/language.ts
  apps/web/middleware.ts
  packages/design-system/src/icons/fill/components/Alert.tsx
Labels: 🥥 제성, Fix
