Repository LO-CO-CO/LOCOCO-CLIENT, pull requests merged in 2025-07, with the labels that each got.

#8 Init(*): Storybook setting
  .gitignore
  apps/web/app/page.tsx
  packages/ui/.storybook/main.ts
  packages/ui/.storybook/preview.ts
  packages/ui/.storybook/vitest.setup.ts
  packages/ui/package.json
  packages/ui/postcss.config.js
  packages/ui/src/button.tsx
  packages/ui/src/card.tsx
  packages/ui/src/code.tsx
  packages/ui/src/components/button/Button.stories.ts
  packages/ui/src/components/button/Button.tsx
  packages/ui/src/components/button/index.ts
  packages/ui/src/components/index.ts
  packages/ui/src/index.ts
  packages/ui/styles.css
  packages/ui/vitest.config.ts
  packages/ui/vitest.shims.d.ts
  pnpm-lock.yaml
Labels: ⚙️ Settings, 🫐 동희

#17 Refactor(*): ui 폴더 네이밍 design-system으로 변경
  .vscode/lococo.code-workspace
  apps/web/app/globals.css
  apps/web/app/page.tsx
  apps/web/package.json
  package.json
  packages/design-system/.storybook/main.ts
  packages/design-system/.storybook/preview.ts
  packages/design-system/.storybook/vitest.setup.ts
  packages/design-system/eslint.config.mjs
  packages/design-system/package.json
  packages/design-system/postcss.config.js
  packages/design-system/src/button.tsx
  packages/design-system/src/card.tsx
  packages/design-system/src/code.tsx
  packages/design-system/src/components/button/Button.stories.ts
  packages/design-system/src/components/button/Button.tsx
  packages/design-system/src/components/button/index.ts
  packages/design-system/src/components/index.ts
  packages/design-system/src/index.ts
  packages/design-system/src/lib/cn.ts
  packages/design-system/styles.css
  packages/design-system/tsconfig.json
  packages/design-system/turbo/generators/config.ts
  packages/design-system/turbo/generators/templates/component.hbs
  packages/design-system/vitest.config.ts
  packages/design-system/vitest.shims.d.ts
  pnpm-lock.yaml
Labels: 🛠️ Refactor, ⚙️ Settings, 🍋 재훈

#14 Init(web): TanStack Query 세팅
  apps/web/app/layout.tsx
  apps/web/package.json
  apps/web/shared/components/providers.tsx
  apps/web/shared/utils/get-query-client.ts
  apps/web/shared/utils/index.ts
  pnpm-lock.yaml
Labels: ⚙️ Settings, 🥝 정은

#22 Init(*): lint 일괄 적용 및 storybook eslint plugin 추가
  apps/web/app/globals.css
  apps/web/eslint.config.js
  apps/web/package.json
  apps/web/postcss.config.js
  packages/design-system/components.json
  packages/design-system/eslint.config.mjs
  packages/design-system/package.json
  packages/design-system/postcss.config.js
  packages/design-system/src/components/ui/button/Button.stories.ts
  packages/design-system/src/components/ui/button/Button.tsx
  packages/design-system/src/components/ui/button/index.ts
  packages/design-system/src/components/ui/index.ts
  packages/design-system/src/components/ui/select/Select.stories.tsx
  packages/design-system/src/components/ui/select/Select.tsx
  packages/design-system/src/components/ui/select/index.ts
  packages/design-system/turbo/generators/templates/component.hbs
  packages/eslint-config/base.js
  packages/eslint-config/next.js
  packages/eslint-config/react-internal.js
  packages/tailwind-config/postcss.config.js
  packages/tailwind-config/shared-styles.css
  pnpm-lock.yaml
Labels: ⚙️ Settings, 🍋 재훈

#23 Init(*): swagger-typescript-api 세팅
  apps/web/api/Auth.ts
  apps/web/api/Product.ts
  apps/web/api/Youtube.ts
  apps/web/api/data-contracts.ts
  apps/web/api/http-client.ts
  package.json
  pnpm-lock.yaml
Labels: ⚙️ Settings, 🍒 희연

#12 Init(*): github action cicd + Code Owner 세팅
  .github/CODEOWNERS
  .github/workflows/ci-cd.yml
  .github/workflows/deploy.yml
  packages/design-system/eslint.config.mjs
  packages/design-system/package.json
  packages/design-system/src/components/button/Button.stories.ts
  packages/design-system/src/components/button/Button.tsx
  packages/design-system/src/components/button/index.ts
  packages/design-system/src/components/index.ts
  packages/design-system/src/components/ui/select/Select.stories.tsx
  packages/design-system/src/components/ui/select/Select.tsx
  packages/design-system/src/components/ui/select/index.ts
  packages/design-system/src/icons/fill/components/ArrowUp.tsx
  packages/design-system/tsconfig.json
  packages/eslint-config/base.js
  packages/eslint-config/next.js
  packages/eslint-config/react-internal.js
  pnpm-lock.yaml
  vercel.json
Labels: ⚙️ Settings, 🍒 희연

#32 Feat(design-system): badge 컴포넌트
  apps/web/app/page.tsx
  packages/design-system/src/components/badge/Badge.stories.ts
  packages/design-system/src/components/badge/Badge.tsx
  packages/design-system/src/components/badge/index.ts
  packages/design-system/src/components/index.ts
Labels: ✨ Feature, 🥥 제성

#38 Refactor(tailwind-config): en body 타이포 line-height 수정
  packages/tailwind-config/shared-styles.css
Labels: 🛠️ Refactor, ⚙️ Settings, 🥝 정은

#35 Feat(design-system): progress 컴포넌트
  packages/design-system/src/components/index.ts
  packages/design-system/src/components/progress/index.ts
  packages/design-system/src/components/progress/progress.stories.ts
  packages/design-system/src/components/progress/progress.tsx
Labels: ✨ Feature, 🫐 동희

#50 Refacor(design-system): 파일명 파스칼로 변경 및 가로/세로 타입 수정
  packages/design-system/src/components/progress/Progress.stories.ts
  packages/design-system/src/components/progress/Progress.tsx
  packages/design-system/src/components/progress/index.ts
Labels: 🛠️ Refactor, 🫐 동희

#44 Feat(design-system): Select 컴포넌트 구현
  packages/design-system/src/components/select/Select.stories.tsx
  packages/design-system/src/components/select/Select.tsx
  packages/design-system/src/icons/fill/components/ArrowDown.tsx
  packages/design-system/src/icons/fill/components/index.tsx
  packages/design-system/src/icons/fill/svg/arrow_down.svg
  packages/design-system/src/icons/fill/svg/arrow_up.svg
Labels: ✨ Feature, 🥝 정은

#52 Feat(*): design system 의존성 개선 및 Checkbox 구현
  apps/web/app/globals.css
  apps/web/app/page.tsx
  apps/web/components.json
  apps/web/package.json
  apps/web/tsconfig.json
  packages/design-system/components.json
  packages/design-system/package.json
  packages/design-system/src/components/checkbox/Checkbox.tsx
  packages/design-system/src/components/checkbox/index.ts
  packages/design-system/src/components/index.ts
  packages/design-system/src/icons/fill/components/Check.tsx
  packages/design-system/src/icons/fill/components/index.tsx
  packages/design-system/src/icons/fill/svg/check.svg
  packages/design-system/src/index.ts
  packages/design-system/styles.css
  packages/design-system/vitest.config.ts
  packages/tailwind-config/package.json
  pnpm-lock.yaml
Labels: 🐞 Bug, ✨ Feature, 🍋 재훈

#64 Feat(design-system): 별점 컴포넌트 제작
  packages/design-system/src/components/star/Star.tsx
  packages/design-system/src/components/star/Start.stories.ts
  packages/design-system/src/icons/fill/components/ErrorFill.tsx
  packages/design-system/src/icons/fill/components/Star.tsx
  packages/design-system/src/icons/fill/components/index.tsx
  packages/design-system/src/icons/fill/svg/star.svg
Labels: ✨ Feature, 🥥 제성

#60 Feat(design-system): checkbox storybook적용
  packages/design-system/src/components/checkbox/Checkbox.stories.tsx
  packages/design-system/src/components/checkbox/Checkbox.tsx
Labels: 📄 Docs, ⚙️ Settings, 🍋 재훈

#62 Feat(design-system): breadcrumb
  packages/design-system/package.json
  packages/design-system/src/components/breadcrumb/Breadcrumb.stories.tsx
  packages/design-system/src/components/breadcrumb/Breadcrumb.tsx
  packages/design-system/src/components/breadcrumb/index.ts
  packages/design-system/src/components/index.ts
  packages/design-system/src/icons/fill/components/HomeFill.tsx
  packages/design-system/src/icons/fill/components/index.tsx
  packages/design-system/src/icons/fill/svg/home_fill.svg
  pnpm-lock.yaml
Labels: ✨ Feature, ⚙️ Settings, 🍋 재훈

#55 Refacor(*): CI push 이벤트 main 브랜치로만 실행되도록 변경
  .github/workflows/ci-cd.yml
Labels: 🛠️ Refactor, 🍒 희연

#67 Refactor(design-system): 버튼 rem 값 수정, outline 버튼 컬러 미적용 문제 해결 / 폰트 관련 문제 공유
  packages/design-system/src/components/button/Button.stories.tsx
  packages/design-system/src/components/button/Button.tsx
  packages/design-system/src/components/button/index.ts
Labels: 🛠️ Refactor, 🍒 희연

#40 Feat(web): Footer
  apps/web/components/footer/footer.tsx
  apps/web/constants/category.ts
  apps/web/types/category.ts
  packages/design-system/src/components/index.ts
  packages/design-system/src/icons/fill/components/ArrowRight.tsx
  packages/design-system/src/icons/fill/components/InstagramFill.tsx
  packages/design-system/src/icons/fill/components/TwitterFill.tsx
  packages/design-system/src/icons/fill/components/index.tsx
  packages/design-system/src/icons/fill/svg/arrow_right.svg
  packages/design-system/src/icons/fill/svg/instagram_fill.svg
  packages/design-system/src/icons/fill/svg/twitter_fill.svg
Labels: ✨ Feature, 🫐 동희

#82 Refactor(web): product type수정
  apps/web/components/card/card-products.tsx
  apps/web/components/card/card-review.tsx
  apps/web/type/product.ts
  apps/web/types/product.ts
  apps/web/types/review.ts
Labels: 🛠️ Refactor, 🥥 제성

#84 Bug(*): 타이포 토큰 적용 오류 수정
  apps/web/components/card/card-products.tsx
  apps/web/components/card/card-review.tsx
  apps/web/components/footer/footer.tsx
  apps/web/components/header/header.tsx
  packages/design-system/src/components/badge/Badge.tsx
  packages/design-system/src/components/breadcrumb/Breadcrumb.tsx
  packages/design-system/src/components/error-notice/ErrorNotice.tsx
  packages/design-system/src/components/input/Input.tsx
  packages/design-system/src/components/tab/Tab.tsx
  packages/design-system/src/components/tag/Tag.tsx
  packages/tailwind-config/shared-styles.css
Labels: 🐞 Bug, 🥝 정은

#77 Feat(design-system): Reaction Button 컴포넌트 구현
  packages/design-system/package.json
  packages/design-system/src/components/index.ts
  packages/design-system/src/components/reaction-toggle/ReactionToggle.stories.tsx
  packages/design-system/src/components/reaction-toggle/ReactionToggle.tsx
  packages/design-system/src/components/reaction-toggle/index.ts
  packages/design-system/src/icons/fill/components/GoodFill.tsx
  packages/design-system/src/icons/fill/components/GoodOutline.tsx
  packages/design-system/src/icons/fill/components/LikeOutline.tsx
  packages/design-system/src/icons/fill/components/index.tsx
  packages/design-system/src/icons/fill/svg/good_fill.svg
  packages/design-system/src/icons/fill/svg/good_outline.svg
  packages/design-system/src/icons/fill/svg/like_outline.svg
  pnpm-lock.yaml
Labels: ✨ Feature, 🥝 정은

#85 Feat(design-system): Textarea 컴포넌트 구현
  packages/design-system/src/components/index.ts
  packages/design-system/src/components/textarea/Textarea.stories.tsx
  packages/design-system/src/components/textarea/Textarea.tsx
  packages/design-system/src/components/textarea/index.ts
Labels: ✨ Feature, 🥝 정은

#92 Feat(web) : Search page 구현
  apps/web/app/search/mockup.ts
  apps/web/app/search/page.tsx
  apps/web/components/search/more-button.tsx
  apps/web/components/search/option-selector.tsx
  apps/web/components/search/search-bread-crumb-section.tsx
  apps/web/components/search/search-products-section.tsx
  apps/web/components/search/search-reviews-section.tsx
  apps/web/constants/option.ts
  apps/web/types/category.ts
  apps/web/types/option.ts
Labels: ✨ Feature, 🫐 동희

#90 Feat(web): 메인 페이지 layout
  apps/web/app/home/components/home-banner.tsx
  apps/web/app/home/components/home-section-product.tsx
  apps/web/app/home/components/home-section-review.tsx
  apps/web/app/home/components/home-update-date.tsx
  apps/web/app/home/components/home.tsx
  apps/web/app/page.tsx
  apps/web/components/card/card-product.tsx
  apps/web/components/card/card-review.tsx
  apps/web/components/search/search-products-section.tsx
  apps/web/mocks/productMock.ts
  apps/web/mocks/reviewMock.ts
  apps/web/next.config.js
  packages/design-system/src/icons/fill/components/ArrowOutward.tsx
  packages/design-system/src/icons/fill/components/JapaneseReview.tsx
  packages/design-system/src/icons/fill/components/KoreanReview.tsx
  packages/design-system/src/icons/fill/components/index.tsx
  packages/design-system/src/icons/fill/svg/arrow_outward.svg
  packages/design-system/src/icons/fill/svg/japaneseReview.svg
  packages/design-system/src/icons/fill/svg/koreanReview.svg
Labels: ✨ Feature, 🥥 제성

#74 Feat(*): 상품 상세 캐러셀 컴포넌트 구현 및 iconButton 디자인시스템 리팩토링
  apps/web/app/home/components/home-section-product.tsx
  apps/web/app/layout.tsx
  apps/web/app/product-detail/components/comment-box.tsx
  apps/web/app/product-detail/components/main-carousel.css
  apps/web/app/product-detail/components/product-detail-main-carousel.tsx
  apps/web/app/product-detail/components/product-detail-section.tsx
  apps/web/app/product-detail/components/product-info-tab.tsx
  apps/web/app/product-detail/components/product-info.tsx
  apps/web/app/product-detail/components/review.tsx
  apps/web/app/product-detail/components/star-rating.tsx
  apps/web/app/product-detail/components/youtube-carousel.css
  apps/web/app/product-detail/components/youtube-carousel.tsx
  apps/web/app/product-detail/page.tsx
  apps/web/package.json
  apps/web/public/images/swiper1.png
  apps/web/public/images/swiper2.png
  apps/web/public/images/swiper3.png
  apps/web/public/images/swiper4.png
  apps/web/public/images/swiper5.png
  apps/web/public/images/swiper6.png
  apps/web/utils/formatJPY.ts
  apps/web/utils/youtube.ts
  packages/design-system/src/components/avatar/Avatar.tsx
  packages/design-system/src/components/button/Button.tsx
  packages/design-system/src/components/icon-button/IconButton.stories.tsx
  packages/design-system/src/components/icon-button/IconButton.tsx
  packages/design-system/src/components/select/Select.tsx
  packages/design-system/src/components/tab/Tab.stories.ts
  packages/design-system/src/components/tab/Tab.tsx
  packages/design-system/src/components/tab/index.ts
  packages/design-system/src/components/tag/Tag.tsx
  packages/design-system/src/icons/fill/components/Add.tsx
  packages/design-system/src/icons/fill/components/Bad.tsx
  packages/design-system/src/icons/fill/components/LikeFill.tsx
  packages/design-system/src/icons/fill/components/Line.tsx
  packages/design-system/src/icons/fill/components/Purchase.tsx
  packages/design-system/src/icons/fill/components/Write.tsx
  packages/design-system/src/icons/fill/components/index.tsx
  packages/design-system/src/icons/fill/svg/add.svg
  packages/design-system/src/icons/fill/svg/bad.svg
  packages/design-system/src/icons/fill/svg/like_fill.svg
  packages/design-system/src/icons/fill/svg/purchase.svg
  packages/design-system/src/icons/fill/svg/write.svg
  packages/tailwind-config/shared-styles.css
  pnpm-lock.yaml
Labels: ✨ Feature, 🛠️ Refactor, 🍋 재훈

#112 Fix(web): 메인 페이지 레이아웃 수정
  apps/web/app/(with-layout)/layout.tsx
  apps/web/app/(with-layout)/page.tsx
  apps/web/app/(with-layout)/product-detail/components/comment-box.tsx
  apps/web/app/(with-layout)/product-detail/components/main-carousel.css
  apps/web/app/(with-layout)/product-detail/components/product-detail-main-carousel.tsx
  apps/web/app/(with-layout)/product-detail/components/product-detail-section.tsx
  apps/web/app/(with-layout)/product-detail/components/product-info-tab.tsx
  apps/web/app/(with-layout)/product-detail/components/product-info.tsx
  apps/web/app/(with-layout)/product-detail/components/review.tsx
  apps/web/app/(with-layout)/product-detail/components/star-rating.tsx
  apps/web/app/(with-layout)/product-detail/components/youtube-carousel.css
  apps/web/app/(with-layout)/product-detail/components/youtube-carousel.tsx
  apps/web/app/(with-layout)/product-detail/page.tsx
Labels: ✨ Feature, 🥥 제성

#105 Feat(web): 리뷰 작성 모달 구현
  apps/web/app/(with-layout)/(home)/components/home-banner.tsx
  apps/web/app/(with-layout)/(home)/components/home-section-product.tsx
  apps/web/app/(with-layout)/(home)/components/home-section-review.tsx
  apps/web/app/(with-layout)/(home)/components/home-update-date.tsx
  apps/web/app/(with-layout)/(home)/components/home.tsx
  apps/web/app/(with-layout)/login/components/loginButton.tsx
  apps/web/app/(with-layout)/login/components/loginTitle.tsx
  apps/web/app/(with-layout)/login/page.tsx
  apps/web/app/(with-layout)/page.tsx
  apps/web/app/(with-layout)/product-detail/@modal/(.)write-review/components/index.ts
  apps/web/app/(with-layout)/product-detail/@modal/(.)write-review/components/media-upload.tsx
  apps/web/app/(with-layout)/product-detail/@modal/(.)write-review/components/negative-review.tsx
  apps/web/app/(with-layout)/product-detail/@modal/(.)write-review/components/positive-review.tsx
  apps/web/app/(with-layout)/product-detail/@modal/(.)write-review/components/product-info.tsx
  apps/web/app/(with-layout)/product-detail/@modal/(.)write-review/components/product-option.tsx
  apps/web/app/(with-layout)/product-detail/@modal/(.)write-review/components/product-rating.tsx
  apps/web/app/(with-layout)/product-detail/@modal/(.)write-review/components/receipt-certification.tsx
  apps/web/app/(with-layout)/product-detail/@modal/(.)write-review/hooks/index.ts
  apps/web/app/(with-layout)/product-detail/@modal/(.)write-review/hooks/useFileUploader.ts
  apps/web/app/(with-layout)/product-detail/@modal/(.)write-review/hooks/useReviewInput.ts
  apps/web/app/(with-layout)/product-detail/@modal/(.)write-review/page.tsx
  apps/web/app/(with-layout)/product-detail/@modal/default.tsx
  apps/web/app/(with-layout)/product-detail/components/product-info.tsx
  apps/web/app/(with-layout)/product-detail/components/star-rating.tsx
  apps/web/app/(with-layout)/product-detail/layout.tsx
  apps/web/app/(with-layout)/product-detail/page.tsx
  apps/web/app/(with-layout)/search/page.tsx
  apps/web/components/input/content-with-label.tsx
  apps/web/components/modal/modal.tsx
  apps/web/constants/review.ts
  apps/web/mocks/searchMock.ts
  apps/web/package.json
  apps/web/types/product.ts
  apps/web/types/review.ts
  packages/design-system/src/components/button/Button.tsx
  packages/design-system/src/components/textarea/Textarea.tsx
  packages/design-system/src/icons/fill/components/Add.tsx
  packages/design-system/src/icons/fill/svg/add.svg
  pnpm-lock.yaml
Labels: ✨ Feature, 🥝 정은

#115 Feat(web): line login 개발 및 쿠키 기반 권한별 라우팅 미들웨어 설정
  apps/web/api/http-client.ts
  apps/web/app/(with-layout)/login/components/loginButton.tsx
  apps/web/app/(with-layout)/login/utils/generateLinLoginUrl.ts
  apps/web/app/api/auth/line/login/components/line-login-client.tsx
  apps/web/app/api/auth/line/login/loading.tsx
  apps/web/app/api/auth/line/login/page.tsx
  apps/web/app/api/auth/line/login/queries/queries.ts
  apps/web/middleware.ts
Labels: ✨ Feature, 🍋 재훈

#117 Feat(web): Header api 연동
  apps/web/api/Auth.ts
  apps/web/app/(with-layout)/search/components/more-button.tsx
  apps/web/app/(with-layout)/search/components/not-found-section.tsx
  apps/web/app/(with-layout)/search/components/search-products-section.tsx
  apps/web/app/(with-layout)/search/components/search-reviews-section.tsx
  apps/web/app/(with-layout)/search/page.client.tsx
  apps/web/app/(with-layout)/search/page.tsx
  apps/web/app/api/api-response.ts
  apps/web/app/api/apiRequest.ts
  apps/web/app/api/product-response.ts
  apps/web/app/api/review-response.ts
  apps/web/components/header/header-content.tsx
  apps/web/components/header/use-header-action.ts
  apps/web/constants/query-key.ts
  apps/web/hooks/headers-api.ts
  apps/web/next.config.js
  tmp-spec.json
Labels: ✨ Feature, 🫐 동희

#129 Build(*): turbo web build 명령어 수정
  package.json
Labels: 🛠️ Refactor, 🍋 재훈

#130 build: vercel build command 변경 (web 모노레포 alias)
  vercel.json
Labels: 🐞 Bug, 🍋 재훈

#137 Refactor(web): search refactor
  apps/web/app/(with-layout)/search/components/not-found-section.tsx
  apps/web/app/(with-layout)/search/components/search-products-section.tsx
  apps/web/components/header/header-content.tsx
  apps/web/components/header/use-header-action.ts
  apps/web/components/header/useHeaderAction.ts
Labels: 🛠️ Refactor, 🫐 동희

#147 Hotfix: line login 인스턴스 변경으로 Access Control Allow Credentials 헤더 추가
  apps/web/app/(with-layout)/login/utils/generateLinLoginUrl.ts
  apps/web/app/api/auth/line/login/apis/index.ts
  apps/web/app/api/auth/line/login/components/line-login-client.tsx
  apps/web/app/api/auth/line/login/types/index.ts
Labels: 🐞 Bug, 🍋 재훈

#144 [Feature]: 제품 상세 페이지 empty view 제작
  apps/web/app/(with-layout)/(home)/components/home-section-review.tsx
  apps/web/app/(with-layout)/layout.tsx
  apps/web/app/(with-layout)/product-detail/[productId]/components/review.tsx
  apps/web/app/(with-layout)/product-detail/[productId]/components/youtube-carousel.tsx
  packages/design-system/src/icons/fill/components/ImgPhoto.tsx
  packages/design-system/src/icons/fill/components/ImgVideo.tsx
  packages/design-system/src/icons/fill/components/index.tsx
  packages/design-system/src/icons/fill/svg/img_photo.svg
  packages/design-system/src/icons/fill/svg/img_video.svg
Labels: ✨ Feature, 🥥 제성

#150 Feat: GTM 태그 설정
  apps/web/app/layout.tsx
Labels: ✨ Feature, ⚙️ Settings, 🍋 재훈

#148 Feat(web) 쿠키를 활용한 로그인 상태로 좋아요 토글 및 헤더 로그인 상태 관리
  apps/web/components/card/card-product.tsx
  apps/web/components/card/hooks/use-product-like.ts
  apps/web/components/header/header-content.tsx
  apps/web/utils/client-cookie.ts
Labels: ✨ Feature, 🥥 제성

#153 Feat(web): 로딩 처리 및 레이아웃 조정, 제품 상세 페이지 내 컴포넌트 추가
  apps/web/app/(with-layout)/(home)/components/home-section-product.tsx
  apps/web/app/(with-layout)/(home)/components/home-section-youtube.tsx
  apps/web/app/(with-layout)/layout.tsx
  apps/web/app/(with-layout)/login/page.tsx
  apps/web/app/(with-layout)/product-detail/[productId]/components/product-bread-crumb-section.tsx
  apps/web/app/(with-layout)/product-detail/[productId]/components/review.tsx
  apps/web/app/(with-layout)/product-detail/[productId]/page.client.tsx
  apps/web/app/(with-layout)/search/page.client.tsx
  apps/web/app/(with-layout)/search/page.tsx
  apps/web/app/favicon.ico
  apps/web/components/header/header-content.tsx
  apps/web/package.json
  pnpm-lock.yaml
Labels: ✨ Feature, 🛠️ Refactor, 🥝 정은

#158 Deploy(web): develop 배포 파이프라인 추가
  .github/workflows/ci-cd.yml
  .github/workflows/deploy.yml
Labels: ⚙️ Settings, 🍋 재훈

#155 Feature(web) : header scroll
  apps/web/app/(with-layout)/page.tsx
  apps/web/app/(with-layout)/search/page.client.tsx
  apps/web/components/header/header-content.tsx
  apps/web/components/header/header.tsx
  apps/web/components/header/use-intersect.ts
Labels: ✨ Feature, 🫐 동희

#160 Bug(web): 클릭되는 요소 변경
  apps/web/.gitignore
  apps/web/app/(with-layout)/(home)/components/home-section-review.tsx
Labels: 🐞 Bug, 🥥 제성

#164 Refactor(web): line login redirect uri queryParams 추가
  apps/web/app/api/auth/line/login/apis/index.ts
  apps/web/app/api/auth/line/login/components/line-login-client.tsx
  apps/web/app/api/auth/line/login/queries/queries.ts
Labels: 🛠️ Refactor, 🍋 재훈

#124 Feat(web) : 리뷰 작성 api 연동
  apps/web/api/Admin.ts
  apps/web/api/Auth.ts
  apps/web/api/Product.ts
  apps/web/api/ProductLike.ts
  apps/web/api/Review.ts
  apps/web/api/client.ts
  apps/web/api/data-contracts.ts
  apps/web/api/http-client.ts
  apps/web/app/(with-layout)/product-detail/[productId]/@modal/(.)write-review/hooks/presignedUrlApi.ts
  apps/web/app/(with-layout)/product-detail/[productId]/@modal/(.)write-review/hooks/reviewApi.ts
  apps/web/app/(with-layout)/product-detail/[productId]/@modal/(.)write-review/hooks/useReviewInput.ts
  apps/web/app/(with-layout)/product-detail/[productId]/@modal/write-review/hooks/presignedUrlApi.ts
  apps/web/app/(with-layout)/product-detail/[productId]/@modal/write-review/hooks/reviewApi.ts
  apps/web/app/(with-layout)/product-detail/[productId]/@modal/write-review/hooks/useFileUploader.ts
  apps/web/app/(with-layout)/product-detail/[productId]/@modal/write-review/hooks/useReviewInput.ts
  apps/web/app/(with-layout)/product-detail/[productId]/@modal/write-review/page.tsx
  apps/web/app/(with-layout)/product-detail/[productId]/components/product-info.tsx
  apps/web/hooks/use-product-api.ts
  packages/design-system/src/icons/fill/components/Vector.tsx
  packages/design-system/src/icons/fill/components/Vector469.tsx
  packages/design-system/src/icons/fill/components/Vector470.tsx
  packages/design-system/src/icons/fill/components/index.tsx
  packages/design-system/src/icons/fill/svg/vector.svg
  packages/design-system/src/icons/fill/svg/vector469.svg
  packages/design-system/src/icons/fill/svg/vector470.svg
  tmp-spec.json
Labels: ✨ Feature, 🫐 동희

#167 Feat(web): 서버에서 전달해준 쿠키 받은 후 좋아요 분기 처리
  apps/web/app/(with-layout)/(home)/components/home-section-product.tsx
  apps/web/app/(with-layout)/(home)/utils/getUserStatus.ts
  apps/web/app/(with-layout)/page.tsx
  apps/web/components/card/card-product.tsx
  apps/web/components/card/hooks/use-product-like.ts
  apps/web/types/product.ts
Labels: ✨ Feature, 🥥 제성

#171 Bug(web): 검증된 유튜브 영상들로 map 대상 변경
  apps/web/app/(with-layout)/product-detail/[productId]/components/youtube-carousel.tsx
Labels: 🐞 Bug, 🥥 제성

#174 Bug(web): 헤더 최상단 버튼 속성 수정 및 z-index 설정
  apps/web/components/header/header-content.tsx
  apps/web/components/header/header.tsx
  packages/design-system/src/components/badge/Badge.tsx
Labels: 🐞 Bug, 🥝 정은

#181 feat(web): 커서 추가 및 상세 페이지 w-full로 변경
  apps/web/app/(with-layout)/product-detail/[productId]/@modal/(.)write-review/components/media-upload.tsx
  apps/web/app/(with-layout)/product-detail/[productId]/@modal/(.)write-review/components/receipt-certification.tsx
  apps/web/app/(with-layout)/product-detail/[productId]/@modal/write-review/components/index.ts
  apps/web/app/(with-layout)/product-detail/[productId]/@modal/write-review/components/media-upload.tsx
  apps/web/app/(with-layout)/product-detail/[productId]/@modal/write-review/components/negative-review.tsx
  apps/web/app/(with-layout)/product-detail/[productId]/@modal/write-review/components/positive-review.tsx
  apps/web/app/(with-layout)/product-detail/[productId]/@modal/write-review/components/product-info.tsx
  apps/web/app/(with-layout)/product-detail/[productId]/@modal/write-review/components/product-option.tsx
  apps/web/app/(with-layout)/product-detail/[productId]/@modal/write-review/components/product-rating.tsx
  apps/web/app/(with-layout)/product-detail/[productId]/@modal/write-review/components/receipt-certification.tsx
  apps/web/app/(with-layout)/product-detail/[productId]/@modal/write-review/hooks/index.ts
  apps/web/app/(with-layout)/product-detail/[productId]/@modal/write-review/hooks/presignedUrlApi.ts
  apps/web/app/(with-layout)/product-detail/[productId]/@modal/write-review/hooks/reviewApi.ts
  apps/web/app/(with-layout)/product-detail/[productId]/@modal/write-review/hooks/useFileUploader.ts
  apps/web/app/(with-layout)/product-detail/[productId]/@modal/write-review/hooks/useReviewInput.ts
  apps/web/app/(with-layout)/product-detail/[productId]/@modal/write-review/page.tsx
  apps/web/app/(with-layout)/product-detail/[productId]/page.client.tsx
Labels: ✨ Feature, 🫐 동희

#161 Feat(web): 리뷰 상세 조회 모달 (image&video 리뷰 / like toggle) api 연동
  apps/web/api/Admin.ts
  apps/web/api/Auth.ts
  apps/web/api/data-contracts.ts
  apps/web/app/(with-layout)/(home)/components/home-section-review.tsx
  apps/web/app/(with-layout)/(home)/utils/getReviewItems.ts
  apps/web/app/(with-layout)/page.tsx
  apps/web/app/(with-layout)/product-detail/[productId]/components/review.tsx
  apps/web/app/(with-layout)/review-modal/[reviewId]/image/page.tsx
  apps/web/app/(with-layout)/review-modal/[reviewId]/video/page.tsx
  apps/web/app/(with-layout)/review-modal/mocks/index.ts
  apps/web/app/review-modal/[reviewId]/image/page.tsx
  apps/web/app/review-modal/[reviewId]/video/page.tsx
  apps/web/app/review-modal/components/comment.tsx
  apps/web/app/review-modal/components/image-carousel.tsx
  apps/web/app/review-modal/components/media-info.tsx
  apps/web/app/review-modal/components/media-viewer.tsx
  apps/web/app/review-modal/components/review-info.tsx
  apps/web/app/review-modal/components/review-modal-layout.tsx
  apps/web/app/review-modal/components/review-modal-swiper.tsx
  apps/web/app/review-modal/components/video-player.tsx
  apps/web/app/review-modal/constants/index.ts
  apps/web/app/review-modal/hooks/review-api.ts
  apps/web/app/review-modal/types/index.ts
  apps/web/constants/query-key.ts
Labels: ✨ Feature, 🍒 희연

#186 Feat(web): loading 구현
  apps/web/components/loading/loading-svg.tsx
Labels: ✨ Feature, 🫐 동희

#187 Feat(web): product-detail 좋아요 api 연동
  apps/web/app/(with-layout)/product-detail/[productId]/components/product-info.tsx
  apps/web/components/card/hooks/use-product-like.ts
Labels: ✨ Feature, 🥥 제성

#193 Fix(web): line login api redirect url querystring 제거
  apps/web/app/api/auth/line/login/apis/index.ts
  apps/web/app/api/auth/line/login/components/line-login-client.tsx
  apps/web/app/api/auth/line/login/queries/queries.ts
Labels: 🛠️ Refactor, 🍋 재훈

#194 Refactor(web): 리뷰 모달에서 상품 정보 클릭 시 해당 상품으로 이동
  apps/web/app/review-modal/[reviewId]/image/page.tsx
  apps/web/app/review-modal/[reviewId]/video/page.tsx
  apps/web/app/review-modal/components/review-info.tsx
  apps/web/app/review-modal/components/review-modal-layout.tsx
  apps/web/app/review-modal/components/review-modal-swiper.tsx
  apps/web/app/review-modal/types/index.ts
Labels: 🛠️ Refactor, 🍒 희연

#195 Feat(*): 작업 중인 페이지 경고 모달
  apps/web/components/modal/pop-up-modal.tsx
  packages/design-system/package.json
  packages/design-system/src/components/dialog/Dialog.tsx
  packages/design-system/src/components/dialog/index.ts
  packages/design-system/src/components/index.ts
  pnpm-lock.yaml
Labels: ✨ Feature, 🥥 제성

#199 Feat(web): 로그인 리다이렉트 과정 로딩 화면 제작
  apps/web/app/api/auth/line/login/components/line-login-client.tsx
Labels: ✨ Feature, 🥥 제성

#202 Feat(web): 제품 상세 페이지 - 리뷰 작성 및 좋아요 api 접근 제한
  apps/web/app/(with-layout)/product-detail/[productId]/components/product-detail-section.tsx
  apps/web/app/(with-layout)/product-detail/[productId]/components/product-info.tsx
  apps/web/app/(with-layout)/product-detail/[productId]/components/review-list.tsx
  apps/web/app/(with-layout)/product-detail/[productId]/components/review.tsx
  apps/web/app/(with-layout)/product-detail/[productId]/components/star-rating.tsx
  apps/web/app/(with-layout)/product-detail/[productId]/page.client.tsx
  apps/web/app/(with-layout)/product-detail/[productId]/page.tsx
  apps/web/components/card/hooks/use-product-like.ts
Labels: ✨ Feature, 🥥 제성

#205 Feat(web): video 플레이어 영상 원본 비율로 플레이
  apps/web/app/review-modal/components/video-player.tsx
Labels: ✨ Feature, 🍒 희연

#209 feat(web): search page qa
  apps/web/app/(with-layout)/search/components/search-bread-crumb-section.tsx
  apps/web/app/(with-layout)/search/page.client.tsx
Labels: ✨ Feature, 🫐 동희

#211 feat(web) : skeleton
  apps/web/app/(with-layout)/(home)/components/home-section-product.tsx
  apps/web/app/(with-layout)/product-detail/[productId]/@modal/(.)write-review/hooks/useReviewInput.ts
  apps/web/app/(with-layout)/product-detail/[productId]/page.tsx
  apps/web/app/(with-layout)/search/components/search-products-section.tsx
  apps/web/app/(with-layout)/search/components/search-reviews-section.tsx
  apps/web/app/(with-layout)/search/hook/use-product-section.ts
  apps/web/app/(with-layout)/search/hook/use-review-section.ts
  apps/web/app/(with-layout)/search/page.client.tsx
  apps/web/app/api/apiRequest.ts
  apps/web/app/review-modal/[reviewId]/image/page.tsx
  apps/web/app/review-modal/[reviewId]/video/page.tsx
  apps/web/components/card/card-skeleton.tsx
  apps/web/components/header/use-header-action.ts
Labels: ✨ Feature, 🫐 동희

#217 Feat(web): 상세페이지 유저 업로드 영상 캐러셀 구현
  apps/web/app/(with-layout)/product-detail/[productId]/apis/index.ts
  apps/web/app/(with-layout)/product-detail/[productId]/components/product-info.tsx
  apps/web/app/(with-layout)/product-detail/[productId]/components/review.tsx
  apps/web/app/(with-layout)/product-detail/[productId]/components/user-upload-video-carousel.tsx
  apps/web/app/(with-layout)/product-detail/[productId]/components/user-uploaded-video-carousel.css
  apps/web/app/(with-layout)/product-detail/[productId]/components/youtube-carousel.tsx
  apps/web/app/(with-layout)/product-detail/[productId]/page.client.tsx
  apps/web/app/(with-layout)/product-detail/[productId]/types/index.ts
Labels: ✨ Feature, 🛠️ Refactor, 🍋 재훈

#215 feat(web): review onboarding
  apps/web/app/review-modal/components/ReviewOnboardingModal.tsx
  packages/design-system/src/icons/fill/components/Vector.tsx
  packages/design-system/src/icons/fill/components/Vector469.tsx
  packages/design-system/src/icons/fill/components/Vector470.tsx
  packages/design-system/src/icons/fill/components/Vector471.tsx
  packages/design-system/src/icons/fill/components/Vector472.tsx
  packages/design-system/src/icons/fill/components/index.tsx
  packages/design-system/src/icons/fill/svg/vector.svg
  packages/design-system/src/icons/fill/svg/vector469.svg
  packages/design-system/src/icons/fill/svg/vector470.svg
  packages/design-system/src/icons/fill/svg/vector471.svg
  packages/design-system/src/icons/fill/svg/vector472.svg
Labels: ✨ Feature, 🫐 동희

#229 feat(web): 리뷰 작성 후, invalidate
  apps/web/app/(with-layout)/product-detail/[productId]/@modal/(.)write-review/hooks/reviewApi.ts
Labels: ✨ Feature, 🫐 동희

#241 Feat(web): detail page
  apps/web/app/(with-layout)/product-detail/[productId]/@modal/(.)delete-review/page.tsx
  apps/web/app/(with-layout)/product-detail/[productId]/apis/index.ts
  apps/web/app/(with-layout)/product-detail/[productId]/components/product-info.tsx
Labels: ✨ Feature, 🫐 동희

#248 Fix(web): 리뷰 모달 조회 에러 수정
  apps/web/app/(with-layout)/(home)/components/home-section-review.tsx
  apps/web/app/(with-layout)/product-detail/[productId]/components/review.tsx
  apps/web/app/(with-layout)/product-detail/[productId]/components/user-upload-video-carousel.tsx
  apps/web/app/(with-layout)/search/components/search-reviews-section.tsx
  apps/web/app/review-modal/[reviewId]/detail/image/page.client.tsx
  apps/web/app/review-modal/[reviewId]/detail/image/page.tsx
  apps/web/app/review-modal/[reviewId]/detail/video/page.client.tsx
  apps/web/app/review-modal/[reviewId]/detail/video/page.tsx
  apps/web/app/review-modal/[reviewId]/home/image/page.client.tsx
  apps/web/app/review-modal/[reviewId]/home/image/page.tsx
  apps/web/app/review-modal/[reviewId]/home/video/page.client.tsx
  apps/web/app/review-modal/[reviewId]/home/video/page.tsx
  apps/web/app/review-modal/[reviewId]/search/image/page.client.tsx
  apps/web/app/review-modal/[reviewId]/search/image/page.tsx
  apps/web/app/review-modal/[reviewId]/search/video/page.client.tsx
  apps/web/app/review-modal/[reviewId]/search/video/page.tsx
  apps/web/app/review-modal/hooks/review-api.ts
Labels: 🐞 Bug, 🍒 희연

#257 Feat(web): 로그인 상태에 따른 쿠키 및 svg 관리
  apps/web/app/(with-layout)/layout.tsx
  apps/web/components/header/header-content.tsx
  apps/web/components/header/header.tsx
  packages/design-system/src/icons/fill/components/Open.tsx
  packages/design-system/src/icons/fill/components/index.tsx
  packages/design-system/src/icons/fill/svg/open.svg
Labels: ✨ Feature, 🥥 제성

#255 fix(web): 카테고리 검색 시 리뷰 조회 안되는 문제 수정
  apps/web/app/(with-layout)/product-detail/[productId]/components/review-list.tsx
  apps/web/app/(with-layout)/search/components/search-reviews-section.tsx
  apps/web/app/review-modal/[reviewId]/detail/video/page.client.tsx
  apps/web/app/review-modal/[reviewId]/search/image/page.client.tsx
  apps/web/app/review-modal/[reviewId]/search/video/page.client.tsx
  apps/web/app/review-modal/hooks/review-api.ts
Labels: 🐞 Bug, 🥝 정은

#263 Feat(web): logout 후에 server component refresh
  apps/web/components/header/header-content.tsx
Labels: ✨ Feature, 🥥 제성

#264 develop to main
  apps/web/components/header/header-content.tsx
Labels: ✨ Feature, 🥥 제성
