Repository LO-CO-CO/LOCOCO-CLIENT, pull requests merged in 2025-09, with the labels that each got.

#304 Feat(design-system): Select 컴포넌트 design-system variation 추가에 따른 대응
  apps/web/app/[locale]/(with-layout)/product-detail/[productId]/@modal/(.)write-review/components/product-option.tsx
  apps/web/app/[locale]/(with-layout)/product-detail/[productId]/components/review.tsx
  apps/web/app/[locale]/not-found.tsx
  packages/design-system/src/components/error-notice/ErrorNotice.tsx
  packages/design-system/src/components/select/Select.stories.tsx
  packages/design-system/src/components/select/Select.tsx
Labels: ✨ Feature, 🥥 제성

#328 Feat(Web): 번역플로우 자동화 구글시트
  apps/web/.gitignore
  apps/web/package.json
  apps/web/translate/download.js
  apps/web/translate/index.js
  apps/web/translate/package.json
  apps/web/translate/upload.js
  pnpm-lock.yaml
Labels: ✨ Feature, 🍋 재훈

#345 Feature/#330/main page UI
  apps/web/app/[locale]/(with-layout)/(home)/all/[page]/page.tsx
  apps/web/app/[locale]/(with-layout)/(home)/components/campaign-all.tsx
  apps/web/app/[locale]/(with-layout)/(home)/components/campaign-language.tsx
  apps/web/app/[locale]/(with-layout)/(home)/components/home-banner.tsx
  apps/web/app/[locale]/(with-layout)/(home)/components/home-section-campaign.tsx
  apps/web/app/[locale]/(with-layout)/(home)/components/home-section-header.tsx
  apps/web/app/[locale]/(with-layout)/(home)/components/home-section-product.tsx
  apps/web/app/[locale]/(with-layout)/(home)/components/home-section-review.tsx
  apps/web/app/[locale]/(with-layout)/(home)/components/home-section-youtube.tsx
  apps/web/app/[locale]/(with-layout)/(home)/components/home-section.tsx
  apps/web/app/[locale]/(with-layout)/(home)/components/server-wrapper/home-product-fallback.tsx
  apps/web/app/[locale]/(with-layout)/(home)/components/server-wrapper/home-product-server.tsx
  apps/web/app/[locale]/(with-layout)/(home)/components/server-wrapper/home-review-fallback.tsx
  apps/web/app/[locale]/(with-layout)/(home)/components/server-wrapper/home-review-server.tsx
  apps/web/app/[locale]/(with-layout)/(home)/components/server-wrapper/home-youtube-fallback.tsx
  apps/web/app/[locale]/(with-layout)/(home)/components/server-wrapper/home-youtube-server.tsx
  apps/web/app/[locale]/(with-layout)/layout.tsx
  apps/web/app/[locale]/(with-layout)/page.tsx
  apps/web/app/[locale]/(with-layout)/product-detail/[productId]/components/product-info-tab.tsx
  apps/web/components/campaign/campaign-filter.tsx
  apps/web/components/campaign/campaign-grid.tsx
  apps/web/components/card/BracketChip.tsx
  apps/web/components/card/Card.tsx
  apps/web/components/card/hooks/use-product-like.ts
  apps/web/components/gnb/gnb-language.tsx
  apps/web/constants/category.ts
  apps/web/constants/language.tsx
  apps/web/messages/en.json
  apps/web/messages/es.json
  apps/web/messages/ko.json
  apps/web/mocks/campaignData.ts
  apps/web/types/category.ts
  packages/design-system/src/components/select/Select.tsx
  packages/design-system/src/components/tab/Tab.stories.tsx
  packages/design-system/src/components/tab/Tab.tsx
Labels: ✨ Feature, 🥥 제성

#334 Feat(web): 역할 선택 모달 컴포넌트 구현
  apps/web/components/sign-up/select-role-modal.tsx
  apps/web/messages/en.json
  packages/design-system/src/components/button/Button.tsx
  packages/design-system/src/components/modal-header/ModalHeader.tsx
Labels: ✨ Feature, 🍒 희연

#338 Feat(web): 사용자 유도 모달 컴포넌트 구현
  apps/web/components/sign-up/select-role-modal.tsx
  apps/web/components/sign-up/user-induction-modal.tsx
  apps/web/messages/en.json
  apps/web/messages/es.json
  apps/web/messages/ko.json
  packages/design-system/src/components/modal-header/ModalHeader.tsx
Labels: ✨ Feature, 🍒 희연

#336 Feat(web): 가입 확인 모달 컴포넌트 구현
  apps/web/app/[locale]/(with-layout)/sign-up/brand/page.tsx
  apps/web/app/[locale]/(with-layout)/sign-up/components/confirm-signup-modal.tsx
  apps/web/app/[locale]/(with-layout)/sign-up/components/select-role-modal.tsx
  apps/web/app/[locale]/(with-layout)/sign-up/components/user-induction-modal.tsx
  apps/web/app/[locale]/(with-layout)/sign-up/creator/sns-links/page.tsx
  apps/web/components/sign-up/confirm-signup-modal.tsx
  apps/web/messages/en.json
  apps/web/messages/es.json
  apps/web/messages/ko.json
Labels: ✨ Feature, 🍒 희연

#354 Feat(web) creator signup form 페이지 UI 구현
  apps/web/app/[locale]/(with-layout)/sign-up/brand/page.tsx
  apps/web/app/[locale]/(with-layout)/sign-up/brand/utils/signup.ts
  apps/web/app/[locale]/(with-layout)/sign-up/creator/components/community-name.tsx
  apps/web/app/[locale]/(with-layout)/sign-up/creator/components/home-address.tsx
  apps/web/app/[locale]/(with-layout)/sign-up/creator/components/index.ts
  apps/web/app/[locale]/(with-layout)/sign-up/creator/components/personal-details.tsx
  apps/web/app/[locale]/(with-layout)/sign-up/creator/components/skin-info.tsx
  apps/web/app/[locale]/(with-layout)/sign-up/creator/page.tsx
  apps/web/app/[locale]/(with-layout)/sign-up/creator/utils/signup.ts
  apps/web/components/forms/CreatorFormSections.tsx
  apps/web/components/forms/PhoneFormField.tsx
  apps/web/components/forms/SelectFormField.tsx
  apps/web/components/forms/TextFormField.tsx
  apps/web/components/forms/index.ts
  apps/web/constants/creator-options.ts
  apps/web/messages/en.json
  apps/web/messages/es.json
  apps/web/messages/ko.json
  apps/web/package.json
  apps/web/utils/birth-date-options.ts
  apps/web/utils/country-options.ts
  apps/web/utils/format-phone-number.ts
  apps/web/utils/index.ts
  packages/design-system/src/components/select/Select.tsx
  packages/design-system/src/icons/fill/components/CheckRound.tsx
  packages/design-system/src/icons/fill/components/SkinTone.tsx
  packages/design-system/src/icons/fill/components/index.tsx
  packages/design-system/src/icons/fill/svg/check_round.svg
  packages/design-system/src/icons/fill/svg/skin_tone.svg
  pnpm-lock.yaml
Labels: ✨ Feature, 🍒 희연

#361 Feat(web): Campaign detail page UI
  apps/web/app/[locale]/(with-layout)/(home)/page.tsx
  apps/web/app/[locale]/(with-layout)/campaign-detail/[campaignId]/components/campaign-carousel.tsx
  apps/web/app/[locale]/(with-layout)/campaign-detail/[campaignId]/components/campaign-detail-image-wrapper.tsx
  apps/web/app/[locale]/(with-layout)/campaign-detail/[campaignId]/components/campaign-info-gray-border-box.tsx
  apps/web/app/[locale]/(with-layout)/campaign-detail/[campaignId]/components/campaign-info-panel.tsx
  apps/web/app/[locale]/(with-layout)/campaign-detail/[campaignId]/page.client.tsx
  apps/web/app/[locale]/(with-layout)/campaign-detail/[campaignId]/page.tsx
  apps/web/app/[locale]/(with-layout)/layout.tsx
  apps/web/app/[locale]/layout.tsx
  apps/web/components/gnb/gnb-auth.tsx
  apps/web/components/gnb/gnb-menu.tsx
  apps/web/components/gnb/gnb.tsx
  apps/web/messages/ko.json
  apps/web/public/images/swiper1.png
  apps/web/public/images/swiper2.png
  apps/web/public/images/swiper3.png
  apps/web/public/images/swiper6.png
  packages/design-system/src/icons/fill/components/Gift.tsx
  packages/design-system/src/icons/fill/components/index.tsx
  packages/design-system/src/icons/fill/svg/gift.svg
Labels: ✨ Feature, 🍋 재훈

#377 Feat(web): translate - 번역사항 반영
  apps/web/messages/en.json
  apps/web/messages/es.json
  apps/web/messages/ko.json
Labels: ✨ Feature, 🍋 재훈

#382 Feat(web): brand signup form api 연동
  apps/web/app/[locale]/(with-layout)/sign-up/brand/apis/brand-form.ts
  apps/web/app/[locale]/(with-layout)/sign-up/brand/hooks/useBrandForm.ts
  apps/web/app/[locale]/(with-layout)/sign-up/brand/page.tsx
  apps/web/app/[locale]/(with-layout)/sign-up/brand/types/brand-form.ts
  apps/web/app/[locale]/(with-layout)/sign-up/brand/utils/api-transformers.ts
  apps/web/app/[locale]/(with-layout)/sign-up/brand/utils/signup.ts
  apps/web/app/[locale]/(with-layout)/sign-up/creator/utils/signup.ts
  apps/web/components/forms/PhoneFormField.tsx
  apps/web/components/forms/SignupFormLayout.tsx
  apps/web/messages/en.json
  apps/web/messages/es.json
  apps/web/messages/ko.json
  apps/web/utils/format-phone-number.ts
  apps/web/utils/index.ts
Labels: ✨ Feature, 🍒 희연

#387 Feat(web): creator_form_page api 연동
  apps/web/app/[locale]/(with-layout)/my-page/connect-sns/page.tsx
  apps/web/app/[locale]/(with-layout)/sign-up/creator/apis/creator-form.ts
  apps/web/app/[locale]/(with-layout)/sign-up/creator/apis/duplicate-check.ts
  apps/web/app/[locale]/(with-layout)/sign-up/creator/components/community-name.tsx
  apps/web/app/[locale]/(with-layout)/sign-up/creator/components/personal-details.tsx
  apps/web/app/[locale]/(with-layout)/sign-up/creator/components/skin-info.tsx
  apps/web/app/[locale]/(with-layout)/sign-up/creator/hooks/useCreatorForm.ts
  apps/web/app/[locale]/(with-layout)/sign-up/creator/page.tsx
  apps/web/app/[locale]/(with-layout)/sign-up/creator/sns-links/hooks/useSnsStatus.ts
  apps/web/app/[locale]/(with-layout)/sign-up/creator/sns-links/page.tsx
  apps/web/app/[locale]/(with-layout)/sign-up/creator/types/creator-form.ts
  apps/web/app/[locale]/(with-layout)/sign-up/creator/types/duplicate-check.ts
  apps/web/app/[locale]/(with-layout)/sign-up/creator/utils/api-transformers.ts
  apps/web/app/[locale]/(with-layout)/sign-up/creator/utils/signup.ts
  apps/web/app/[locale]/(with-layout)/sign-up/queries/query-keys.ts
  apps/web/app/[locale]/(with-layout)/sign-up/queries/useIdAvailability.ts
  apps/web/app/api/apiRequest.ts
  apps/web/components/forms/CreatorFormSections.tsx
  apps/web/components/forms/SignupFormLayout.tsx
  apps/web/components/forms/SnsConnection.tsx
  apps/web/components/forms/TextFormField.tsx
  apps/web/components/sign-up/select-role-modal.tsx
  apps/web/constants/creator-options.ts
  apps/web/constants/query-key.ts
  apps/web/hooks/use-connect-sns.ts
  apps/web/messages/en.json
  apps/web/messages/es.json
  apps/web/messages/ko.json
  apps/web/swagger-codegen/Auth.ts
  apps/web/swagger-codegen/Brand.ts
  apps/web/swagger-codegen/Campaign.ts
  apps/web/swagger-codegen/CampaignReview.ts
  apps/web/swagger-codegen/Creator.ts
  apps/web/swagger-codegen/CreatorCampaign.ts
  apps/web/swagger-codegen/Customer.ts
  apps/web/swagger-codegen/Migration.ts
  apps/web/swagger-codegen/Product.ts
  apps/web/swagger-codegen/SnsConnection.ts
  apps/web/swagger-codegen/User.ts
  apps/web/swagger-codegen/data-contracts.ts
  packages/design-system/src/components/input/Input.tsx
Labels: ✨ Feature, 🍒 희연

#385 Feat(web): 브랜드 마이페이지 - 내 캠페인 API 연동
  apps/web/app/[locale]/(with-layout)/brand/api/index.ts
  apps/web/app/[locale]/(with-layout)/brand/campaign/card-grid-section.tsx
  apps/web/app/[locale]/(with-layout)/brand/campaign/page.tsx
  apps/web/app/[locale]/(with-layout)/brand/hooks/useBrandCampaign.ts
  apps/web/components/campaign/campaign-grid.tsx
  apps/web/components/card/BracketChip.tsx
  apps/web/components/card/Card.tsx
  apps/web/components/empty/campgin-list-empty.tsx
  packages/design-system/src/icons/fill/components/EmptyImage.tsx
  packages/design-system/src/icons/fill/components/index.tsx
  packages/design-system/src/icons/fill/svg/empty_image.svg
Labels: ✨ Feature, 🥥 제성

#383 Feat(web): 브랜드 마이페이지 프로필 편집 UI
  apps/web/app/[locale]/(with-layout)/brand/layout.tsx
  apps/web/app/[locale]/(with-layout)/brand/profile/component/address-info.tsx
  apps/web/app/[locale]/(with-layout)/brand/profile/component/basic-info.tsx
  apps/web/app/[locale]/(with-layout)/brand/profile/component/image-section.tsx
  apps/web/app/[locale]/(with-layout)/brand/profile/page.tsx
  apps/web/components/forms/CreatorFormSections.tsx
  apps/web/components/forms/FormSection.tsx
  apps/web/messages/en.json
  apps/web/messages/es.json
  apps/web/messages/ko.json
  apps/web/schema/brand-profile-edit.ts
Labels: ✨ Feature, 🥥 제성

#399 Feat(web): 브랜드 마이페이지 - 새 캠페인 생성 api 연동
  apps/web/api/getPresignedUrl.ts
  apps/web/app/[locale]/(with-layout)/brand/component/create-campaign/campaign-due-date.tsx
  apps/web/app/[locale]/(with-layout)/brand/component/create-campaign/campaign-end-info.tsx
  apps/web/app/[locale]/(with-layout)/brand/component/create-campaign/campaign-start-info.tsx
  apps/web/app/[locale]/(with-layout)/brand/component/create-campaign/campaign-winner-announce.tsx
  apps/web/app/[locale]/(with-layout)/brand/create-campaign/[id]/page.tsx
  apps/web/app/[locale]/(with-layout)/brand/create-campaign/api/index.ts
  apps/web/app/[locale]/(with-layout)/brand/create-campaign/component/campaign-form.tsx
  apps/web/app/[locale]/(with-layout)/brand/create-campaign/page.tsx
  apps/web/app/[locale]/(with-layout)/brand/create-campaign/utils/api-form-converter.ts
  apps/web/app/[locale]/(with-layout)/brand/hooks/useCampaignForm.ts
  apps/web/app/[locale]/(with-layout)/brand/hooks/useFileUpload.ts
  apps/web/components/campaign/campaign-upload-media.tsx
  apps/web/components/drag-drop/DargDropArea.tsx
  apps/web/components/forms/SelectFormField.tsx
  apps/web/schema/create-campaign-schema.ts
  apps/web/swagger-codegen/CampaignReview.ts
  apps/web/swagger-codegen/SnsConnection.ts
  apps/web/swagger-codegen/data-contracts.ts
  apps/web/utils/getErrorMessage.ts
Labels: ✨ Feature, 🥥 제성

#403 Feat(web): how it work qa
  apps/web/app/[locale]/(with-layout)/how-it-work/components/brand.tsx
  apps/web/app/[locale]/(with-layout)/how-it-work/components/creators.tsx
  apps/web/app/[locale]/(with-layout)/how-it-work/components/q-and-a.tsx
Labels: ✨ Feature, 🫐 동희

#410 Feat(web): final review page
  apps/web/app/[locale]/(with-layout)/my-page/components/content-submissions/brand-note.tsx
  apps/web/app/[locale]/(with-layout)/my-page/connect-sns/page.tsx
  apps/web/app/[locale]/(with-layout)/my-page/constant/queryKey.ts
  apps/web/app/[locale]/(with-layout)/my-page/content-submissions/page.tsx
  apps/web/app/[locale]/(with-layout)/my-page/edit-profile/page.tsx
  apps/web/app/[locale]/(with-layout)/my-page/final-review/components/content-type.tsx
  apps/web/app/[locale]/(with-layout)/my-page/final-review/components/final-wrapper.tsx
  apps/web/app/[locale]/(with-layout)/my-page/final-review/components/image-box.tsx
  apps/web/app/[locale]/(with-layout)/my-page/final-review/page.tsx
  apps/web/app/[locale]/(with-layout)/my-page/hooks/use-my-campaign.ts
  apps/web/app/[locale]/(with-layout)/my-page/hooks/use-review-result.ts
  apps/web/app/[locale]/(with-layout)/my-page/my-campaign/page.tsx
  apps/web/components/empty/campgin-list-empty.tsx
  apps/web/messages/en.json
  apps/web/messages/es.json
  apps/web/messages/ko.json
  apps/web/swagger-codegen/data-contracts.ts
Labels: ✨ Feature, 🫐 동희

#412 Feat(web): brand layout
  apps/web/app/[locale]/(with-layout)/brand/campaign/card-grid-section.tsx
  apps/web/app/[locale]/(with-layout)/brand/campaign/page.tsx
  apps/web/app/[locale]/(with-layout)/brand/create-campaign/component/campaign-form.tsx
  apps/web/app/[locale]/(with-layout)/brand/layout.tsx
  apps/web/app/[locale]/(with-layout)/brand/profile/component/basic-info.tsx
  apps/web/app/[locale]/(with-layout)/brand/profile/page.tsx
  apps/web/components/forms/TextFormField.tsx
  apps/web/components/side-bar/side-bar.tsx
Labels: ✨ Feature, 🫐 동희

#414 Feat(Web): skin tone 옵션 추가, 주소 최대 글자수 수정 QA
  apps/web/app/[locale]/(with-layout)/sign-up/creator/utils/signup.ts
  apps/web/constants/creator-options.ts
  apps/web/messages/en.json
  apps/web/messages/es.json
  apps/web/messages/ko.json
Labels: ✨ Feature, 🍒 희연
