Repository LO-CO-CO/LOCOCO-CLIENT, pull requests merged in 2025-08, with the labels that each got.

#283 Feat(*): Jira 연동
  .github/ISSUE_TEMPLATE/bug-template.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/ISSUE_TEMPLATE/issue-form.yml
  .github/ISSUE_TEMPLATE/refactor-template.md
  .github/workflows/close-jira-issue.yml
  .github/workflows/create-jira-issue.yml
Labels: ✨ Feature, ⚙️ Settings, 🥝 정은

#294 Refactor(web): 온보딩 모달 노출 여부 판단 로직 개선
  apps/web/app/review-modal/[reviewId]/detail/image/page.client.tsx
  apps/web/app/review-modal/[reviewId]/detail/video/page.client.tsx
  apps/web/app/review-modal/[reviewId]/home/image/page.client.tsx
  apps/web/app/review-modal/[reviewId]/home/video/page.client.tsx
  apps/web/app/review-modal/[reviewId]/search/image/page.client.tsx
  apps/web/app/review-modal/[reviewId]/search/video/page.client.tsx
  apps/web/app/review-modal/components/index.ts
  apps/web/app/review-modal/components/media/image-carousel.tsx
  apps/web/app/review-modal/components/media/index.ts
  apps/web/app/review-modal/components/media/media-info.tsx
  apps/web/app/review-modal/components/media/media-viewer.tsx
  apps/web/app/review-modal/components/media/video-player.tsx
  apps/web/app/review-modal/components/modal-structure/ReviewModalContent.tsx
  apps/web/app/review-modal/components/modal-structure/ReviewOnboardingModal.tsx
  apps/web/app/review-modal/components/modal-structure/index.ts
  apps/web/app/review-modal/components/modal-structure/review-modal-layout.tsx
  apps/web/app/review-modal/components/modal-structure/review-modal-swiper.tsx
  apps/web/app/review-modal/components/review/comment.tsx
  apps/web/app/review-modal/components/review/index.ts
  apps/web/app/review-modal/components/review/review-info.tsx
  apps/web/app/review-modal/constants/index.ts
  apps/web/app/review-modal/hooks/useReviewModalData.ts
  apps/web/hooks/useModalClose.ts
  apps/web/package.json
  pnpm-lock.yaml
Labels: 🛠️ Refactor, 🍒 희연

#292 Refactor(web): 리뷰 모달 페이지 폴더 구조 개선 및 dayjs 적용
  apps/web/app/review-modal/components/media/media-viewer.tsx
  apps/web/app/review-modal/components/modal-structure/ReviewModalContent.tsx
  apps/web/app/review-modal/components/modal-structure/review-modal-swiper.tsx
  apps/web/app/review-modal/components/review/review-info.tsx
  apps/web/app/review-modal/hooks/useReviewDataTransformer.ts
  apps/web/app/review-modal/hooks/useReviewDetailData.ts
  apps/web/app/review-modal/hooks/useReviewListData.ts
  apps/web/app/review-modal/hooks/useReviewModalData.ts
  apps/web/app/review-modal/hooks/useReviewModalParams.ts
  apps/web/package.json
  pnpm-lock.yaml
Labels: 🛠️ Refactor, 🍒 희연

#280 Refactor(web): header
  apps/web/app/(with-layout)/search/components/not-found-section.tsx
  apps/web/app/(with-layout)/search/components/option-selector.tsx
  apps/web/app/(with-layout)/search/components/product-not-found.tsx
  apps/web/app/(with-layout)/search/components/review-not-found.tsx
  apps/web/app/(with-layout)/search/components/search-bread-crumb-section.tsx
  apps/web/app/(with-layout)/search/components/search-products-section.tsx
  apps/web/app/(with-layout)/search/components/search-reviews-section.tsx
  apps/web/app/(with-layout)/search/hook/use-product-section.ts
  apps/web/app/(with-layout)/search/hook/use-review-section.ts
  apps/web/app/(with-layout)/search/page.client.tsx
  apps/web/app/(with-layout)/search/page.tsx
  apps/web/app/(with-layout)/search/types/search.ts
  apps/web/app/api/product-response.ts
  apps/web/app/api/review-response.ts
  apps/web/components/header/category-option-bar.tsx
  apps/web/components/header/category-section.tsx
  apps/web/components/header/header-content.tsx
  apps/web/components/header/header.tsx
  apps/web/components/header/hooks/use-header-action.ts
  apps/web/components/header/main-header.tsx
  apps/web/components/header/search-bar.tsx
  apps/web/components/header/top-util.tsx
  apps/web/components/header/use-intersect.ts
  apps/web/components/header/use-scroll-header.ts
  apps/web/components/header/utils/get-url.ts
  apps/web/constants/option.ts
  apps/web/hooks/headers-api.ts
  apps/web/swagger-codegen/Product.ts
  apps/web/swagger-codegen/Review.ts
  apps/web/swagger-codegen/data-contracts.ts
  apps/web/types/option.ts
  apps/web/utils/category.ts
Labels: ✨ Feature, 🫐 동희
